server:
  port: 8080

cloud:
  aws:
    credentials:
      session-token: FwoGZXIvYXdzEKT//////////wEaDFKI9I0TcIoWsCPRiiK4AW+7QufoyZ5KMQ7YPqmd9DkYbpwISj1ZdoY8NiYfhDgnTm1X1t5PiJFJy12nFHVEEsnXSiKE3pqMJdTt3cdu/KMLveL0aMhaWCtMfhsDBbu+KZmQiAQ4KN/KuTsZF14OxHHlMrQJthEw5jpxDTbxyCbo5P7/5rHuhlhY2u6IPXQ5BBSfJ4dYaaG+q98gwAiiF+BldvdlHwzLorzPJq7T3Ic22xenYxMdrXNQhdeEl63JOmGZ4ZbR9IAoh/X0ogYyLTZaHfeY867O3AFS8k1nkOTQkHqXu8d+9WOFN5jNBNoj7uDC0Xvcxi2fixR7Lw==
      access-key: ASIA27OCY5S4YVL4I5PI
      secret-key: +hur5mjkknFtDxl5xy14lSDZiaY0uKaNVlSdASzt
    region:
      static: us-east-1
    stack:
      auto: false

application:
  security:
    jwt:
      secret-key: 34753778214125442A472D4A614E645267556B58703273357638792F423F4528
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
  bucket:
    name: javanime

spring:
  profiles:
    active:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 6MB
      max-request-size: 10MB

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

  logging:
    pattern:
      console: "%d %-5level %logger : %msg%n"
    level:
      org.springframework: info
      org.hibernate: debug